### ISSUE TITLE
Write onboarding guide for people interested in running CSSclasses in new cities

### ISSUE THREAD

**Issue by bastianalbers** [CSSclasses/CSSclasses#13] opened 2015-10-28 09:38 UTC
I got some interest by people who might want to run a CSSclasses in their city. The guide should include:
* core values that are not to be messed with to be an "official" CSSclasses
* what do i need (room, coaches)
* how to i coach
* how can i engage people
* how to get help from us

**Comment by Kriesse** [comment] 2016-06-22 10:40
Dupe of #28

**Closed by Kriesse** 2016-06-22 10:40 UTC
Labels: Content, help wanted
