### ISSUE TITLE
Oval social media icons

### ISSUE THREAD

**Issue by kolletzki** [CSSclasses/CSSclasses#69] opened 2017-03-23 09:06 UTC
I assume the social media icons on the page are supposed to be displayed round, but they are displayed oval. This affects the icons in the footer but also the about page.

![](https://i.imgur.com/4nbwhOa.png)
![](https://i.imgur.com/TMTI0ne.png)

Browser: Firefox 52.0.1
OS: Windows 10 Pro (14393.953)

**Comment by lukaszklis** [comment] 2017-03-23 09:47
Hey @kolletzki, thanks for submitting this. Would you like to take a look into the icon-scaling issue? I’m occupied with other projects at the moment, and might not have time within the next couple of weeks to fix it.

**Comment by verpixelt** [comment] 2017-07-15 10:20
Cannot reproduce this behaviour anymore. Gonna close the issue for now.

**Closed by verpixelt** 2017-07-15 10:20 UTC
